### ISSUE TITLE
Saving bookmarks doesn't list any existing bookmarks or folders to save to 

### ISSUE THREAD

**Issue by mongoliving** [FirefoxCSSThemers/WhiteSur-Tweaked#4]
Hey,

I recently commented on this WhiteSur3 on deviantart and I've noticed that the saving bookmarks window doesn't list any existing bookmarks or folders to save to. You can see in the attached image that I have bookmarks for sure and that the "Computer" folder is missing 
<img width="1145" alt="Screen Shot 2021-08-05 at 20 05 20" src="https://user-images.githubusercontent.com/86615159/128399862-f6914ede-c86b-4158-a1d8-140d7c903489.png">

**Comment by mongoliving** [comment]
This was dumb of me... - I clicked the arrow in light mode and then the bookmarks shows up

I think the arrow's appearance is wrong however.. downwards pointing arrow should in my view list available items where the rightwards pointing arrow should be the one be seen as closing the tree view? 
Am I wrong about this?

**Comment by AlfarexGuy2019** [comment]
Hi!
Sorry for the late reply, our time zones do not match : )
Anyway, could we know which version of WhiteSur are you using?

**Comment by mongoliving** [comment]
> Anyway, could we know which version of WhiteSur are you using?
I was using the most recent beta of White Sur.
WhiteSur-V3-beta-2
https://github.com/FirefoxCSSThemers/WhiteSur-Tweaked/releases/tag/v3.0-beta-2

The behaviour of the arrows you present is the direct opposite of how the Firefox browser presents the bookmark arrows. 
Expanded vs non-expanded tree

**Comment by AlfarexGuy2019** [comment]
generally the bookmarks are not supposed to be used with the theme, so we didn't pay much attention to bookmarks.

**Comment by mongoliving** [comment]
That's of course alright 👍🏻  I wish you and your team continued success with WhiteSur.

**Comment by AlfarexGuy2019** [comment]
Thank you!
