### ISSUE TITLE
Bookmarks window in dark mode is blinding - limits of Firefox theming?

### ISSUE THREAD

**Issue by mongoliving** [FirefoxCSSThemers/WhiteSur-Tweaked#5]
Second thing, again for dark mode as my previous issue; bookmarks window in dark mode is blinding.

Is this within the limits of Firefox theming?
I've learned over the years that there's things that Firefox won't allow getting themed no matter how much effort you put into doing so. Not with CSS anyway.

<img width="1067" alt="Screen Shot 2021-08-05 at 20 06 46" src="https://user-images.githubusercontent.com/86615159/128400338-d4c7413d-867c-48f9-860d-613811a4d709.png">

**Comment by AlfarexGuy2019** [comment]
As far as I can see, it seems like you might have been singing the song and sent me the screenshot in light mode. Have you enabled Light Mode macOS-wide?

**Comment by mongoliving** [comment]
That's odd - I think it must have been a user error. I can't remember if I was using dark theme or light mode for this , but using dark mode with the release I was using at the time does yield this exact appearance .. Also the title of that song is "Blinded by the lights" And no, I don't listen to it - I just know it is the title of the song. I am sorry for being a doucebag.

**Comment by AlfarexGuy2019** [comment]
Ah No prob 😄
